export const refs = {
  header: document.querySelector('.header'),
  headerLogo: document.querySelector('.header__link'),
  homeBtnHeader: document.querySelector('.home-header'),
  libraryBtnHeader: document.querySelector('.library-header'),
  libraryNavigation: document.querySelector('.library-navigation'),
  searchMovie: document.querySelector('.search-film-form'),
  searchErrors: document.querySelector('.search-errors'),
  watchedBtnHeader: document.querySelector('.watched-header'),
  queueBtnHeader: document.querySelector('.queue-header'),
  hero: document.getElementById('filmList'),
  pagination: document.querySelector('.pagination__container'),
  paginationPrevious: document.querySelector('.arrow_left'),
  paginationFirst: document.querySelector('.first-page'),
  paginationAll: document.querySelector('.all-pages'),
  paginationLast: document.querySelector('.last-page'),
  paginationNext: document.querySelector('.arrow_right'),
  nIceTeam: document.querySelector('.team-modal-btn'),
  modalSearch: document.querySelector('.backdrop-modal-form'),
};
